[package]
name = "ethcore-ipc-hypervisor"
version = "1.2.0"
authors = ["Nikolay Volf <nikolay@ethcore.io>"]
license = "GPL-3.0"
build = "build.rs"

[features]

[dependencies]
ethcore-ipc = { path = "../rpc" }
nanomsg = { git = "https://github.com/thehydroimpulse/nanomsg.rs.git", features = ["bundled"] }
ethcore-ipc-nano = { path = "../nano" }
semver = "0.2"
log = "0.3"

[build-dependencies]
ethcore-ipc-codegen = { path = "../codegen" }
