[package]
description = "Generic transaction pool."
name = "transaction-pool"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = "0.11"
log = "0.3"
smallvec = "0.4"
trace-time = { path = "../util/trace-time", version = "0.1" }

[dev-dependencies]
ethereum-types = "0.3"
