[package]
description = "Fetching hash-addressed content."
repository = "https://github.com/openethereum/openethereum"
license = "GPL-3.0"
name = "parity-hash-fetch"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
call-contract = { package = "ethcore-call-contract", path = "../../ethcore/call-contract" }
futures = "0.1"
log = "0.4"
mime = "0.3"
mime_guess = "2.0.1"
rand = "0.7.3"
rustc-hex = "2.1.0"
fetch = { path = "../../util/fetch" }
parity-bytes = "0.1"
ethereum-types = "0.9.0"
parity-runtime = { git = "https://github.com/vorot93/parity-common", branch = "tokio-compat" }
keccak-hash = "0.5.0"
registrar = { path = "../../util/registrar" }
types = { path = "../../ethcore/types", package = "common-types" }

ethabi = "12.0"
ethabi-derive = "12.0"
ethabi-contract = "11.0"

[dev-dependencies]
parking_lot = "0.10.0"
fake-fetch = { path = "../../util/fake-fetch" }
