[package]
description = "Mutex with cached len, for use with collections"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "len-caching-mutex"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
parking_lot = "0.6"
