[package]
description = "WASM Interpreter"
name = "wasm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
byteorder = "1.0"
ethereum-types = "0.8.0"
log = "0.4"
parity-wasm = "0.31"
libc = "0.2"
pwasm-utils = "0.6.1"
vm = { path = "../vm" }
wasmi = "0.3.0"

[dev-dependencies]
env_logger = "0.5"
