[package]
description = "Rust bindings for tinykeccak C library"
homepage = "https://github.com/paritytech/keccak-hash"
readme = "README.md"
license = "GPL-3.0"
name = "keccak-hash"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[dependencies]
ethereum-types = "0.3"
tiny-keccak = "1.3"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
tempdir = "0.3"
