[package]
name = "triehash-ethereum"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Trie-root helpers, ethereum style"
license = "GPL-3.0"

[dependencies]
triehash = "0.8.0"
ethereum-types = "0.6.0"
keccak-hasher = { path = "../keccak-hasher" }
