[package]
name = "blooms-db"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
byteorder = "1.2"
ethbloom = "0.5"
parking_lot = "0.6"
tiny-keccak = "1.4"

[dev-dependencies]
tempdir = "0.3"
