[package]
name = "blooms-db"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ethbloom = "0.9.1"
parking_lot = "0.10.0"

[dev-dependencies]
criterion = "0.3"
tempfile = "3.1"

[[bench]]
name = "blooms"
harness = false
