[package]
name = "blooms-db"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
byteorder = "1.2"
ethbloom = "=0.5.0"
parking_lot = "0.7"
tiny-keccak = "1.4"

[dev-dependencies]
criterion = "0.3.0"
tempdir = "0.3"
