[package]
name = "blooms-db"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ethbloom = "0.6.4"
parking_lot = "0.7"

[dev-dependencies]
tempdir = "0.3"
