[package]
description = "HTTP/HTTPS fetching library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "fetch"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1"
futures-cpupool = "0.1"
parking_lot = "0.5"
log = "0.4"

hyper = "0.11"
hyper-rustls = "0.12"
tokio-core = "0.1"

[features]
default = []
