[package]
description = "HTTP/HTTPS fetching library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "fetch"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
futures = "0.1"
hyper = "~0.12.9"
hyper-rustls = "0.18"
http = "0.1"
log = "0.4"
tokio = "0.1.22"
url = "2"
bytes = "0.4"

[features]
default = []
