stages:
  - build
  - test
  - deploy
variables:
  GIT_DEPTH: "3"
  SIMPLECOV: "true" 
  RUST_BACKTRACE: "1"
cache:
  key: "$CI_BUILD_NAME/$CI_BUILD_REF_NAME"
  untracked: true
linux-stable:
  stage: build
  image: ethcore/rust:stable
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - export
    - cargo build --release --verbose
    - strip target/release/parity
    - mkdir -p x86_64-unknown-linux-gnu/stable
    - cp target/release/parity x86_64-unknown-linux-gnu/stable/parity
  tags:
    - rust
    - rust-stable
  artifacts:
    paths:
    - x86_64-unknown-linux-gnu/stable/parity
    name: "stable-x86_64-unknown-linux-gnu_parity"
linux-beta:
  stage: build
  image: ethcore/rust:beta
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - export
    - cargo build --release --verbose
    - strip target/release/parity
    - mkdir -p x86_64-unknown-linux-gnu/beta
    - cp target/release/parity x86_64-unknown-linux-gnu/beta/parity
  tags:
    - rust
    - rust-beta
  artifacts:
    paths:
    - x86_64-unknown-linux-gnu/beta/parity
    name: "beta-x86_64-unknown-linux-gnu_parity"
linux-nightly:
  stage: build
  image: ethcore/rust:nightly
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - cargo build --release --verbose
    - strip target/release/parity
    - mkdir -p x86_64-unknown-linux-gnu/nightly
    - cp target/release/parity x86_64-unknown-linux-gnu/nigthly/parity
  tags:
    - rust
    - rust-nightly
  artifacts:
    paths:
    - x86_64-unknown-linux-gnu/nigthly/parity
    name: "nigthly-x86_64-unknown-linux-gnu_parity"
  allow_failure: true
linux-centos:
  stage: build
  image: ethcore/rust-centos:latest
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - export CXX="g++"
    - export CC="gcc"
    - cargo build --release --verbose
    - strip target/release/parity
    - mkdir -p x86_64-unknown-linux-gnu/centos
    - cp target/release/parity x86_64-unknown-linux-gnu/centos/parity
  tags:
    - rust
    - rust-centos
  artifacts:
    paths:
    - x86_64-unknown-linux-gnu/centos/parity
    name: "centos-x86_64-unknown-linux-gnu_parity"
linux-armv7:
  stage: build
  image: ethcore/rust-arm:latest
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - export
    - rm -rf .cargo
    - mkdir -p .cargo
    - echo "[target.armv7-unknown-linux-gnueabihf]" >> .cargo/config
    - echo "linker= \"arm-linux-gnueabihf-gcc\"" >> .cargo/config
    - cat .cargo/config
    - cargo build --target armv7-unknown-linux-gnueabihf --release --verbose
    - arm-linux-gnueabihf-strip target/armv7-unknown-linux-gnueabihf/release/parity
    - mkdir -p armv7_unknown_linux_gnueabihf
    - cp target/release/party armv7_unknown_linux_gnueabihf/parity
  tags:
    - rust
    - rust-arm
  artifacts:
    paths:
    - armv7-unknown-linux-gnueabihf/parity
    name: "armv7_unknown_linux_gnueabihf_parity"
  allow_failure: true
linux-arm:
  stage: build
  image: ethcore/rust-arm:latest
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - export
    - rm -rf .cargo
    - mkdir -p .cargo
    - echo "[target.arm-unknown-linux-gnueabihf]" >> .cargo/config
    - echo "linker= \"arm-linux-gnueabihf-gcc\"" >> .cargo/config
    - cat .cargo/config
    - cargo build --target arm-unknown-linux-gnueabihf --release --verbose
    - arm-linux-gnueabihf-strip target/arm-unknown-linux-gnueabihf/release/parity
    - mkdir -p arm-unknown-linux-gnueabihf
    - cp target/release/parity arm-unknown-linux-gnueabihf/parity
  tags:
    - rust
    - rust-arm
  artifacts:
    paths:
    - arm-unknown-linux-gnueabihf/parity
    name: "arm-unknown-linux-gnueabihf_parity"
  allow_failure: true
linux-armv6:
  stage: build
  image: ethcore/rust-arm:latest
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - export
    - rm -rf .cargo
    - mkdir -p .cargo
    - echo "[target.arm-unknown-linux-gnueabi]" >> .cargo/config
    - echo "linker= \"arm-linux-gnueabi-gcc\"" >> .cargo/config
    - cat .cargo/config
    - cargo build --target arm-unknown-linux-gnueabi --release --verbose
    - arm-linux-gnueabi-strip target/arm-unknown-linux-gnueabi/release/parity
    - mkdir -p arm-unknown-linux-gnueabi
    - cp target/release/parity arm-unknown-linux-gnueabi/parity
  tags:
    - rust
    - rust-arm
  artifacts:
    paths:
    - arm-unknown-linux-gnueabi/parity
    name: "arm-unknown-linux-gnueabi_parity"
  allow_failure: true
linux-aarch64:
  stage: build
  image: ethcore/rust-arm:latest
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - export
    - rm -rf .cargo
    - mkdir -p .cargo
    - echo "[target.aarch64-unknown-linux-gnu]" >> .cargo/config
    - echo "linker= \"aarch64-linux-gnu-gcc\"" >> .cargo/config
    - cat .cargo/config
    - cargo build --target aarch64-unknown-linux-gnu --release --verbose
    - aarch64-linux-gnu-strip target/aarch64-unknown-linux-gnu/release/parity
    - mkdir -p aarch64-unknown-linux-gnu
    - cp target/release/parity aarch64-unknown-linux-gnu/parity
  tags:
    - rust
    - rust-arm
  artifacts:
    paths:
    - aarch64-unknown-linux-gnu/parity
    name: "aarch64-unknown-linux-gnu_parity"
  allow_failure: true
darwin:
  stage: build
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - cargo build --release --verbose
    - mkdir -p x86_64-apple-darwin
    - cp target/release/parity x86_64-apple-darwin/parity
  tags:
    - osx
  artifacts:
    paths:
    - x86_64-apple-darwin/parity
    name: "x86_64-apple-darwin_parity"
windows:
  stage: build
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - set INCLUDE=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Include;C:\vs2015\VC\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
    - set LIB=C:\vs2015\VC\lib;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10240.0\ucrt\x64
    - set RUST_BACKTRACE=1
    - rustup default stable-x86_64-pc-windows-msvc
    - cargo build --release --verbose
  tags:
   - rust-windows
  artifacts:
    paths:
    - target/release/parity.exe
    - target/release/parity.pdb
    name: "x86_64-pc-windows-msvc_parity"
test-linux:
  stage: test
  before_script:
    - git submodule update --init --recursive
  script:
    - ./test.sh --verbose
  tags:
    - rust-test
  dependencies:
    - linux-stable
deploy-binaries:
  stage: deploy
  only:
    - master
    - beta
    - tags
    - stable
  script:
    - scripts/deploy.sh
