stages:
  - test
  - build
  - publish
  - optional

image:                             parity/rust-parity-ethereum-build:xenial
variables:
  GIT_STRATEGY:                    fetch
  GIT_SUBMODULE_STRATEGY:          recursive
  CI_SERVER_NAME:                  "GitLab CI"
  CARGO_TARGET:                    x86_64-unknown-linux-gnu

.no_git:                           &no_git # disable git strategy
  variables:
    GIT_STRATEGY:                  none
    GIT_SUBMODULE_STRATEGY:        none

.releaseable_branches:             # list of git refs for building GitLab artifacts (think "pre-release binaries")
  only:                            &releaseable_branches
    - stable
    - beta
    - tags
    - schedules

.collect_artifacts:                &collect_artifacts
  artifacts:
    name:                          "${CI_JOB_NAME}_${SCHEDULE_TAG:-${CI_COMMIT_REF_NAME}}"
    when:                          on_success
    expire_in:                     1 mos
    paths:
      - artifacts/

.docker-cache-status:              &docker-cache-status
  variables:
    CARGO_HOME:                    "/ci-cache/parity-ethereum/cargo/${CI_JOB_NAME}"
  dependencies:                    []
  before_script:
    - SCCACHE_ERROR_LOG=/builds/parity/parity-ethereum/sccache_debug.log
        RUST_LOG=sccache=debug
        sccache --start-server
    - sccache -s
  after_script:
    # sccache debug info
    - if test -e sccache_debug.log;
      then
        echo "_____sccache_debug.log listing start:_____";
        cat sccache_debug.log;
        echo "_____sccache_debug.log listing end_____";
        echo "All crate-types:";
        grep 'parse_arguments.*--crate-type' sccache_debug.log | sed -re 's/.*"--crate-type", "([^"]+)".*/\1/' | sort | uniq -c;
        echo "_____Non-cacheable reasons:_____";
        grep CannotCache sccache_debug.log | sed -re 's/.*CannotCache\((.+)\).*/\1/' | sort | uniq -c;
      else
        echo "_____No logs from sccache_____";
        exit 0;
      fi
  tags:
    - linux-docker

.build-on-linux:                   &build-on-linux
  stage:                           build
  <<:                              *docker-cache-status
  <<:                              *collect_artifacts
  script:
    - scripts/gitlab/build-linux.sh
    - sccache -s


cargo-check 0 3:
  stage:                           test
  <<:                              *docker-cache-status
  script:
    - time cargo check --target $CARGO_TARGET --locked --no-default-features --verbose --color=always
    - sccache -s

cargo-check 1 3:
  stage:                           test
  <<:                              *docker-cache-status
  script:
    - time cargo check --target $CARGO_TARGET --locked --manifest-path util/io/Cargo.toml --no-default-features --verbose --color=always
    - sccache -s

cargo-check 2 3:
  stage:                           test
  <<:                              *docker-cache-status
  script:
    - time cargo check --target $CARGO_TARGET --locked --manifest-path util/io/Cargo.toml --features "mio" --verbose --color=always
    - sccache -s

cargo-audit:
  stage:                           test
  <<:                              *docker-cache-status
  script:
    - cargo audit

validate-chainspecs:
  stage:                           test
  <<:                              *docker-cache-status
  script:
    - ./scripts/gitlab/validate-chainspecs.sh
    - sccache -s

test-cpp:
  stage:                           build
  <<:                              *docker-cache-status
  script:
    - ./scripts/gitlab/test-cpp.sh
    - sccache -s

test-linux:
  stage:                           build
  <<:                              *docker-cache-status
  script:
    - ./scripts/gitlab/test-linux.sh stable
    - sccache -s

test-linux-beta:
  stage:                           build
  only:                            *releaseable_branches
  <<:                              *docker-cache-status
  script:
    - ./scripts/gitlab/test-linux.sh beta
    - sccache -s

test-linux-nightly:
  stage:                           build
  only:                            *releaseable_branches
  <<:                              *docker-cache-status
  script:
    - ./scripts/gitlab/test-linux.sh nightly
    - sccache -s
  allow_failure:                   true

build-android:
  <<:                              *build-on-linux
  image:                           parity/rust-parity-ethereum-android-build:stretch
  variables:
    CARGO_TARGET:                  armv7-linux-androideabi

build-linux:
  <<:                              *build-on-linux
  only:                            *releaseable_branches

build-linux-i386:
  <<:                              *build-on-linux
  only:                            *releaseable_branches
  image:                           parity/rust-parity-ethereum-build:i386
  variables:
    CARGO_TARGET:                  i686-unknown-linux-gnu

build-linux-arm64:
  <<:                              *build-on-linux
  only:                            *releaseable_branches
  image:                           parity/rust-parity-ethereum-build:arm64
  variables:
    CARGO_TARGET:                  aarch64-unknown-linux-gnu

build-linux-armhf:
  <<:                              *build-on-linux
  only:                            *releaseable_branches
  image:                           parity/rust-parity-ethereum-build:armhf
  variables:
    CARGO_TARGET:                  armv7-unknown-linux-gnueabihf

build-darwin:
  stage:                           build
  <<:                              *collect_artifacts
  only:                            *releaseable_branches
  variables:
    CARGO_TARGET:                  x86_64-apple-darwin
    CARGO_HOME:                    "${CI_PROJECT_DIR}/.cargo"
    CC:                            gcc
    CXX:                           g++
  script:
    - scripts/gitlab/build-linux.sh
  tags:
    - rust-osx

build-windows:
  stage:                           build
  <<:                              *collect_artifacts
  only:                            *releaseable_branches
  variables:
    CARGO_TARGET:                  x86_64-pc-windows-msvc
    CARGO_HOME:                    "C:/ci-cache/parity-ethereum/cargo/$CI_JOB_NAME"
    GIT_SUBMODULE_STRATEGY:        none
  script:
    - sh scripts/gitlab/build-windows.sh
  tags:
    - rust-windows

publish-docker:
  stage:                           publish
  only:                            *releaseable_branches
  cache:                           {}
  dependencies:
    - build-linux
  tags:
    - shell
  script:
    - scripts/gitlab/publish-docker.sh parity

publish-snap:                      &publish-snap
  stage:                           publish
  only:                            *releaseable_branches
  <<:                              *collect_artifacts
  image:                           snapcore/snapcraft
  variables:
    BUILD_ARCH:                    amd64
  cache:                           {}
  dependencies:
    - build-linux
  tags:
    - linux-docker
  script:
    - scripts/gitlab/publish-snap.sh

publish-snap-i386:
  <<:                              *publish-snap
  variables:
    BUILD_ARCH:                    i386
  dependencies:
    - build-linux-i386

publish-snap-arm64:
  <<:                              *publish-snap
  variables:
    BUILD_ARCH:                    arm64
  dependencies:
    - build-linux-arm64

publish-snap-armhf:
  <<:                              *publish-snap
  variables:
    BUILD_ARCH:                    armhf
  dependencies:
    - build-linux-armhf

publish-onchain:
  stage:                           publish
  only:                            *releaseable_branches
  cache:                           {}
  dependencies:
    - build-linux
    - build-darwin
    - build-windows
  script:
    - scripts/gitlab/publish-onchain.sh
  tags:
    - linux-docker

publish-awss3-release:
  image:                           parity/awscli:latest
  stage:                           publish
  only:                            *releaseable_branches
  <<:                              *no_git
  cache:                           {}
  dependencies:
    - build-linux
    - build-darwin
    - build-windows
  script:
    - echo "__________Push binaries to AWS S3____________"
    - case "${SCHEDULE_TAG:-${CI_COMMIT_REF_NAME}}" in
       (beta|stable|nightly)
         export BUCKET=releases.parity.io/ethereum;
         ;;
       (*)
         export BUCKET=builds-parity;
         ;;
     esac
    - aws s3 sync ./artifacts s3://${BUCKET}/${SCHEDULE_TAG:-${CI_COMMIT_REF_NAME}}/
    - echo "__________Read from S3____________"
    - aws s3 ls s3://${BUCKET}/${SCHEDULE_TAG:-${CI_COMMIT_REF_NAME}} --recursive --human-readable --summarize
  tags:
    - linux-docker

publish-docs:
  stage:                            publish
  image:                            parity/rust-parity-ethereum-docs:xenial
  only:
    - tags
  except:
    - nightly
  cache:                            {}
  dependencies:                     []
  script:
    - scripts/gitlab/publish-docs.sh
  tags:
    - linux-docker
