stages:
  - test
  - build
  - publish
  - optional

image:                             parity/rust:gitlab-ci

variables:
  CI_SERVER_NAME:                  "GitLab CI"
  CARGO_HOME:                      "${CI_PROJECT_DIR}/.cargo"
  CARGO_TARGET:                    x86_64-unknown-linux-gnu

.releaseable_branches:             # list of git refs for building GitLab artifacts (think "pre-release binaries")
  only:                            &releaseable_branches
    - stable
    - beta
    - tags
    - schedules


.collect_artifacts:                &collect_artifacts
  artifacts:
    name:                          "${CI_JOB_NAME}_${SCHEDULE_TAG:-${CI_COMMIT_REF_NAME}}"
    when:                          on_success
    expire_in:                     1 mos
    paths:
    - artifacts/

.determine_version:                &determine_version
  - VERSION="$(sed -r -n '1,/^version/s/^version = "([^"]+)".*$/\1/p' Cargo.toml)"
  - DATE_STR="$(date +%Y%m%d)"
  - ID_SHORT="$(echo ${CI_COMMIT_SHA} | cut -c 1-7)"
  - test "${SCHEDULE_TAG:-${CI_COMMIT_REF_NAME}}" = "nightly" && VERSION="${VERSION}-${ID_SHORT}-${DATE_STR}"
  - export VERSION
  - echo "Version = ${VERSION}"

test-linux:
  stage:                           test
  variables:
    RUN_TESTS:                     all
  script:
    - scripts/gitlab/test-all.sh stable
  tags:
    - rust-stable

test-audit:
  stage:                           test
  script:
    - scripts/gitlab/cargo-audit.sh
  tags:
    - rust-stable

build-linux:
  stage:                           build
  only:                            *releaseable_branches
  script:
    - scripts/gitlab/build-unix.sh
  <<:                              *collect_artifacts
  tags:
    - rust-stable

build-darwin:
  stage:                           build
  only:                            *releaseable_branches
  variables:
    CARGO_TARGET:                  x86_64-apple-darwin
    CC:                            gcc
    CXX:                           g++
  script:
    - scripts/gitlab/build-unix.sh
  tags:
    - rust-osx
  <<:                              *collect_artifacts

build-windows:
  stage:                           build
  only:                            *releaseable_branches
  variables:
    CARGO_TARGET:                  x86_64-pc-windows-msvc
  script:
    - sh scripts/gitlab/build-windows.sh
  tags:
   - rust-windows
  <<:                              *collect_artifacts

publish-docker:
  stage:                           publish
  only:                            *releaseable_branches
  cache: {}
  dependencies:
    - build-linux
  tags:
    - shell
  script:
    - scripts/gitlab/publish-docker.sh parity

publish-snap:
  stage:                           publish
  only:                            *releaseable_branches
  image:                           parity/snapcraft:gitlab-ci
  variables:
    BUILD_ARCH:                  amd64
  cache: {}
  before_script:                   *determine_version
  dependencies:
    - build-linux
  tags:
    - rust-stable
  script:
    - scripts/gitlab/publish-snap.sh
  allow_failure:                   true
  <<:                              *collect_artifacts

publish-awss3:
  stage:                           publish
  only:                            *releaseable_branches
  cache: {}
  dependencies:
    - build-linux
    - build-darwin
    - build-windows
  before_script:                   *determine_version
  script:
    - scripts/gitlab/publish-awss3.sh
  tags:
    - shell

publish-docs:
  stage:                            publish
  only:
    - tags
  except:
    - nightly
  cache: {}
  script:
    - scripts/gitlab/publish-docs.sh
  tags:
    - linux-docker

build-android:
  stage:                           optional
  image:                           parity/rust-android:gitlab-ci
  variables:
    CARGO_TARGET:                  armv7-linux-androideabi
  script:
    - scripts/gitlab/build-unix.sh
  tags:
    - linux-docker
  allow_failure:                   true
  <<:                              *collect_artifacts

test-beta:
  stage:                           optional
  variables:
    RUN_TESTS:                     cargo
  script:
    - scripts/gitlab/test-all.sh beta
  tags:
    - rust-beta
  allow_failure:                   true

test-nightly:
  stage:                           optional
  variables:
    RUN_TESTS:                     all
  script:
    - scripts/gitlab/test-all.sh nightly
  tags:
    - rust-nightly
  allow_failure:                   true
