language: rust

sudo: required

services: docker

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

matrix:
  include:

    # GNU/Linux - Rust Stable Test
    - env: TARGET=x86_64-unknown-linux-gnu
      stage: test
      name: Cargo Test
      rust: stable
      script: $TRAVIS_BUILD_DIR/test.sh

    # GNU/Linux - Deploy GÃ¶rli Node
    - env: TARGET=x86_64-unknown-linux-gnu
      name: Cargo Test
      stage: deploy
      rust: stable
      script: $TRAVIS_BUILD_DIR/target/debug/parity --chain goerli

    # GNU/Linux - Deploy Clique Network
    - env: TARGET=x86_64-unknown-linux-gnu
      name: Cargo Test
      stage: deploy
      rust: stable
      script: $TRAVIS_BUILD_DIR/clique.sh

cache:
  - $HOME/.cargo
  - $TRAVIS_BUILD_DIR/target
before_cache:
  - chmod -R a+r $HOME/.cargo
  - chmod -R a+r $TRAVIS_BUILD_DIR

before_script:
  - rustup self update
  - source ~/.cargo/env || true

after_success: |
  echo "@TODO"
