environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc

branches:
  only:
    - master
    - /^beta-.*$/
    - /^stable-.*$/
    - /^beta$/
    - /^stable$/

install:
  - git submodule update --init --recursive
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.9.0-x86_64-pc-windows-msvc.exe"
  - ps: Start-FileDownload "https://github.com/ethcore/win-build/raw/master/SimpleFC.dll" -FileName nsis\SimpleFC.dll
  - ps: Start-FileDownload "https://github.com/ethcore/win-build/raw/master/vc_redist.x64.exe" -FileName nsis\vc_redist.x64.exe
  - rust-1.9.0-x86_64-pc-windows-msvc.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin;C:\Program Files (x86)\NSIS
  - rustc -V
  - cargo -V

build: off

test_script:
  - cargo test --verbose --release

after_test:
  - cargo build --verbose --release
  - makensis.exe nsis\installer.nsi

artifacts:
  - path: nsis\installer.exe
    name: Windows Installer (x86_64)

cache:
  - target
  - C:\users\appveyor\.cargo -> appveyor.yml
