[package]
description = "Ethereum state machine"
name = "machine"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[[bench]]
name = "builtin_contract"
harness = false
required-features = ["test-helpers"]

[dependencies]
account-state = { path = "../account-state" }
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
crossbeam-utils = "0.7.2"
ethabi = "12.0"
ethabi-contract = "11.0"
ethabi-derive = "12.0"
ethcore-builtin = { path = "../builtin" }
ethcore-call-contract = { path = "../call-contract" }
ethcore-io = { path = "../../util/io" }
ethereum-types = "0.9.1"
# Used for tests in other crates through the `test-helpers` feature
ethjson = { path = "../../json", optional = true }
evm = { path = "../evm" }
keccak-hash = "0.5.0"
log = "0.4"
lru-cache = "0.1.2"
parity-bytes = "0.1.0"
parking_lot = "0.10.0"
rlp = "0.4.5"
state-db = { path = "../state-db" }
trace = { path = "../trace" }
trie-vm-factories = { path = "../trie-vm-factories" }
vm = { path = "../vm" }

[dev-dependencies]
common-types = { path = "../types", features = ["test-helpers"] }
criterion = "0.3"
ethcore = { path = "../", features = ["test-helpers"] }
ethcore-io = { path = "../../util/io" }
ethjson = { path = "../../json" }
parity-crypto = { version = "0.6.1", features = ["publickey"] }
hex-literal = "0.2.1"
spec = { path = "../spec" }
tempfile = "3.1"
trace = { path = "../trace" }

[features]
test-helpers = ["ethjson"]
