[package]
description = "Rpc test client."
name = "rpctest"
version = "1.7.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ctrlc = { git = "https://github.com/ethcore/rust-ctrlc.git" }
docopt = "0.6"
rustc-serialize = "0.3"
ethcore = { path = "../../ethcore" }
ethcore-devtools = { path = "../../devtools" }
ethcore-rpc = { path = ".." }
ethcore-util = { path = "../../util" }
ethjson = { path = "../../json" }
serde_json = "0.8"
