[package]
name = "ethash"
version = "1.9.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]

[dependencies]
log = "0.3"
hash = { path = "../util/hash" }
primal = "0.2.3"
parking_lot = "0.4"
crunchy = "0.1.0"
memmap = "0.5.2"
either = "1.0.0"

[features]
benches = []
