[package]
name = "ethash"
version = "1.7.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]

[dependencies]
log = "0.3"
sha3 = { path = "../util/sha3" }
primal = "0.2.3"
parking_lot = "0.3"
