[package]
description = "Ethcore jsonrpc"
name = "ethcore-rpc"
version = "1.1.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]
build = "build.rs"

[lib]

[dependencies]
log = "0.3"
serde = "0.7.0"
serde_json = "0.7.0"
jsonrpc-core = { git = "https://github.com/tomusdrw/jsonrpc-core.git" }
jsonrpc-http-server = { git = "https://github.com/tomusdrw/jsonrpc-http-server.git", version = "5.1.0" }
ethcore-util = { path = "../util" }
ethcore = { path = "../ethcore" }
ethash = { path = "../ethash" }
ethsync = { path = "../sync" }
ethminer = { path = "../miner" }
rustc-serialize = "0.3"
transient-hashmap = "0.1"
serde_macros = { version = "0.7.0", optional = true }
clippy = { version = "0.0.64", optional = true}

[build-dependencies]
serde_codegen = { version = "0.7.0", optional = true }
syntex = "0.31.0"

[features]
default = ["serde_codegen"]
nightly = ["serde_macros"]
dev = ["clippy", "ethcore/dev", "ethcore-util/dev", "ethsync/dev", "ethminer/dev"]
