[package]
name = "ethcore-ipc"
version = "1.7.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"

[features]

[dependencies]
ethcore-devtools = { path = "../../devtools" }
nanomsg = { git = "https://github.com/ethcore/nanomsg.rs.git" }
ethcore-util = { path = "../../util" }
semver = "0.5"
