[package]
name = "ethcore-ipc"
version = "1.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"

[features]

[dependencies]
ethcore-devtools = { path = "../../devtools" }
nanomsg = { git = "https://github.com/paritytech/nanomsg.rs.git", branch = "parity-1.7" }
ethcore-bigint = { path = "../../util/bigint"}
ethcore-util = { path = "../../util" }
semver = "0.6"
