[package]
description = "Parity Ethereum Chain Specification"
name = "chainspec"
version = "0.1.0"
authors = ["Marek Kotewicz <marek@parity.io>"]

[dependencies]
ethjson = { path = "../json" }
serde_json = "1.0"
