[package]
description = "Parity Updater Service."
name = "parity-updater"
version = "1.9.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.3"
ethabi = "4.0"
target_info = "0.1"
semver = "0.6"
ethcore = { path = "../ethcore" }
ethsync = { path = "../sync" }
ethcore-bytes = { path = "../util/bytes" }
ethereum-types = "0.1"
futures = "0.1"
parking_lot = "0.5"
parity-hash-fetch = { path = "../hash-fetch" }
parity-reactor = { path = "../util/reactor" }
parity-version = { path = "../util/version" }
path = { path = "../util/path" }
