[package]
description = "Parity Updater Service."
name = "parity-updater"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
keccak-hash = { path = "../util/hash" }
lazy_static = "1.0"
log = "0.3"
ethabi = "5.1"
ethabi-derive = "5.0"
ethabi-contract = "5.0"
target_info = "0.1"
semver = "0.9"
ethcore = { path = "../ethcore" }
ethcore-bytes = { path = "../util/bytes" }
ethcore-sync = { path = "../ethcore/sync" }
ethereum-types = "0.3"
parking_lot = "0.6"
parity-hash-fetch = { path = "../hash-fetch" }
parity-version = { path = "../util/version" }
path = { path = "../util/path" }
rand = "0.4"

[dev-dependencies]
ethcore = { path = "../ethcore", features = ["test-helpers"] }
tempdir = "0.3"
matches = "0.1"
