[package]
description = "Parity Ethereum Keys Generator"
name = "ethkey"
version = "0.4.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
edit-distance = "2.0"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
parity-crypto = { version = "0.4.2", features = ["publickey"] }
parity-wordlist = "1.3"
