[package]
description = "Ethcore DB access utilities"
repository = "https://github.com/OpenEthereum/open-ethereum"
license = "GPL-3.0"
name = "ethcore-db"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
common-types = { path = "../types" }
ethereum-types = "0.8.0"
kvdb = "0.4.0"
parity-util-mem = "0.5.1"
parking_lot = "0.10.0"
rlp = "0.4.0"
rlp-derive = "0.1"
