[package]
name = "evmbin"
description = "Parity's EVM implementation"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[[bin]]
name = "parity-evm"
path = "./src/main.rs"

[dependencies]
rustc-serialize = "0.3"
docopt = { version = "0.7" }
ethcore = { path = "../ethcore" }
ethcore-util = { path = "../util" }

[features]
evm-debug = ["ethcore/evm-debug-tests"]
