[package]
name = "whisper-cli"
description = "Whisper command line interface"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"

[dependencies]
ethcore-network-devp2p = { path = "../../util/network-devp2p" }
ethcore-network = { path = "../../util/network" }
ethcore-logger = { path = "../../logger" }
parity-whisper = { path = "../" }
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
panic_hook = { path = "../../util/panic_hook" }
jsonrpc-core = { git = "https://github.com/c0gent/jsonrpc.git", branch = "c0gent-hyper" }
jsonrpc-pubsub = { git = "https://github.com/c0gent/jsonrpc.git", branch = "c0gent-hyper" }
jsonrpc-http-server = { git = "https://github.com/c0gent/jsonrpc.git", branch = "c0gent-hyper" }
log = "0.4"

[[bin]]
name = "whisper"
path = "src/main.rs"
