[package]
name = "whisper-cli"
description = "Whisper command line interface"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"

[dependencies]
docopt = "1.0"
env_logger = "0.5"
ethcore-network = { path = "../../util/network" }
ethcore-network-devp2p = { path = "../../util/network-devp2p" }
jsonrpc-core = "10.0.1"
jsonrpc-http-server = "10.0.1"
jsonrpc-pubsub = "10.0.1"
log = "0.4"
panic_hook = { path = "../../util/panic-hook" }
parity-whisper = { path = "../" }
serde = "1.0"
serde_derive = "1.0"

[[bin]]
name = "whisper"
path = "src/main.rs"
