[package]
name = "triehash"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "in memory patricia trie operations"
license = "GPL-3.0"

[dependencies]
elastic-array = "0.10"
rlp = { version = "0.2.1", path = "../rlp" }
ethereum-types = "0.2"
keccak-hash = { version = "0.1", path = "../hash" }

[dev-dependencies]
trie-standardmap = { path = "../trie-standardmap" }
