[package]
description = "Ethcore IO library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-io"
version = "1.7.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
mio = { git = "https://github.com/ethcore/mio" }
crossbeam = "0.2"
parking_lot = "0.3"
log = "0.3"
slab = "0.2"

