[package]
description = "Ethcore network library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-network"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
error-chain = { version = "0.12", default-features = false }
parity-crypto = "0.3.0"
ethcore-io = { path = "../io" }
ethereum-types = "0.4"
ethkey = { path = "../../accounts/ethkey" }
ipnetwork = "0.12.6"
rlp = { version = "0.3.0", features = ["ethereum"] }
libc = "0.2"
parity-snappy = "0.1"

[dev-dependencies]
assert_matches = "1.2"
