[package]
description = "Ethcore network library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-network"
version = "1.9.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.3"
mio = "0.6.8"
bytes = "0.4"
rand = "0.3.12"
time = "0.1.34"
tiny-keccak = "1.3"
rust-crypto = "0.2.34"
slab = "0.2"
clippy = { version = "0.0.103", optional = true}
igd = "0.6"
libc = "0.2.7"
parking_lot = "0.4"
ansi_term = "0.9"
rustc-hex = "1.0"
ethcore-io = { path = "../io" }
ethcore-util = { path = ".." }
ethcore-bigint = { path = "../bigint" }
ethcore-bytes = { path = "../bytes" }
ethkey = { path = "../../ethkey" }
ethcrypto = { path = "../../ethcrypto" }
rlp = { path = "../rlp" }
path = { path = "../path" }
ethcore-logger = { path ="../../logger" }
ipnetwork = "0.12.6"
hash = { path = "../hash" }
snappy = { path = "../snappy" }
serde_json = "1.0"
error-chain = { version = "0.11", default-features = false }

[dev-dependencies]
ethcore-devtools = { path = "../../devtools" }
tempdir = "0.3"

[features]
default = []
dev = ["clippy"]
