[package]
description = "Ethcore network library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-network"
version = "1.11.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethcore-io = { path = "../io" }
ethereum-types = "0.3"
ethkey = { path = "../../ethkey" }
ethcrypto = { path = "../../ethcrypto" }
rlp = { path = "../rlp" }
ipnetwork = "0.12.6"
snappy = { git = "https://github.com/paritytech/rust-snappy" }
error-chain = { version = "0.11", default-features = false }
