[package]
name = "evm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
bit-set = "0.4"
ethereum-types = "0.3"
heapsize = "0.4"
lazy_static = "1.0"
log = "0.3"
vm = { path = "../vm" }
keccak-hash = { git = "https://github.com/paritytech/parity-common" }
parking_lot = "0.6"
memory-cache = { path = "../../util/memory_cache" }

[dev-dependencies]
rustc-hex = "1.0"

[features]
evm-debug = []
evm-debug-tests = ["evm-debug"]
