[package]
description = "OpenEthereum RPC Client"
homepage = "https://github.com/openethereum/openethereum"
license = "GPL-3.0"
name = "parity-rpc-client"
version = "1.4.0"
authors = ["Parity <admin@parity.io>"]

[dependencies]
ethereum-types = "0.4"
futures = "0.1"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
url = "2"
matches = "0.1"
parking_lot = "0.9"
jsonrpc-core = "15.0.0"
jsonrpc-ws-server = "15.0.0"
parity-rpc = { path = "../../rpc" }
keccak-hash = "0.1"
