[package]
description = "DevP2P implementation of the ethcore network library"
repository = "https://github.com/openethereum/openethereum"
license = "GPL-3.0"
name = "ethcore-network-devp2p"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ansi_term = "0.11"
bytes = "0.4"
derive_more = "0.99"
enr = { version = "0.1.0-alpha.5", default-features = false, features = ["rust-secp256k1"] }
ethcore-io = { path = "../io", features = ["mio"] }
ethereum-types = "0.8.0"
igd = "0.10.0"
ipnetwork = "0.12.6"
keccak-hash = "0.4.0"
libc = "0.2.7"
log = "0.4"
lru-cache = "0.1"
mio = "0.6.8"
natpmp = "0.2"
network = { package = "ethcore-network", path = "../network" }
parity-bytes = "0.1"
parity-crypto = { version = "0.5.0", features = ["publickey"] }
parity-path = "0.1"
parity-snappy = "0.1"
parking_lot = "0.10.0"
rand = "0.7"
rlp = "0.4.0"
secp256k1 = "0.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slab = "0.2"
tiny-keccak = "1.4"

[dev-dependencies]
assert_matches = "1.2"
env_logger = "0.5"
hex-literal = "0.2.1"
tempfile = "3.1"

[features]
default = []
