[package]
description = "Ethcore development/test/build tools"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-devtools"
version = "1.11.0"
authors = ["Parity Technologies <admin@parity.io>"]
