[package]
name = "ethkey"
version = "0.2.0"
authors = ["Ethcore <admin@ethcore.io>"]

[dependencies]
rand = "0.3.14"
lazy_static = "0.2"
tiny-keccak = "1.0"
eth-secp256k1 = { git = "https://github.com/ethcore/rust-secp256k1" }
rustc-serialize = "0.3"
docopt = { version = "0.6", optional = true }
ethcore-bigint = { path = "../util/bigint" }

[features]
default = []
cli = ["docopt"]

[[bin]]
name = "ethkey"
path = "src/bin/main.rs"
doc = false
