[package]
description = "OpenEthereum Blockchain Database, Test Generator, Configuration, Caching, Importing Blocks, and Block Information"
repository = "https://github.com/openethereum/openethereum"
license = "GPL-3.0"
name = "ethcore-blockchain"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
ansi_term = "0.11"
blooms-db = { path = "../../util/blooms-db" }
common-types = { path = "../types" }
ethcore-db = { path = "../db" }
ethereum-types = "0.9.0"
keccak-hash = "0.5.0"
parity-util-mem = "0.6.0"
itertools = "0.8.2"
kvdb = "0.5.0"
log = "0.4"
parity-bytes = "0.1"
rand = "0.7.3"
parking_lot = "0.10.0"
rayon = "1.0"
rlp = "0.4.5"
rlp_compress = { path = "../../util/rlp-compress" }
rlp-derive = "0.1"
triehash-ethereum = { version = "0.2",  path = "../../util/triehash-ethereum" }

[dev-dependencies]
env_logger = "0.5"
parity-crypto = { version = "0.6.2", features = ["publickey"] }
rustc-hex = "2.1.0"
tempfile = "3.1"
kvdb-memorydb = "0.5.0"
