[package]
description = "Parity Miner interface."
name = "ethcore-miner"
homepage = "http://parity.io"
license = "GPL-3.0"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
# Only work_notify, consider a separate crate
ethash = { path = "../ethash" }
fetch = { path = "../util/fetch" }
hyper = "0.11"
parity-reactor = { path = "../util/reactor" }
url = "1"

# Miner
ansi_term = "0.10"
error-chain = "0.11"
ethcore-transaction = { path = "../ethcore/transaction" }
ethereum-types = "0.3"
futures = "0.1"
futures-cpupool = "0.1"
heapsize = "0.4"
keccak-hash = { path = "../util/hash" }
linked-hash-map = "0.5"
log = "0.3"
parking_lot = "0.5"
price-info = { path = "../price-info" }
rayon = "1.0"
trace-time = { path = "../util/trace-time" }
transaction-pool = { path = "../transaction-pool" }

[dev-dependencies]
env_logger = "0.4"
ethkey = { path = "../ethkey" }
rustc-hex = "1.0"
