[package]
name = "parity-whisper"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Whisper Protocol implementation for Parity"

[dependencies]
bitflags = "0.9"
byteorder = "1.0.0"
ethereum-types = "0.3"
ethcore-network = { path = "../util/network" }
ethcore-crypto = { path = "../ethcore/crypto" }
ethkey = { path = "../ethkey" }
hex = "0.2"
log = "0.3"
mem = { path = "../util/mem" }
ordered-float = "0.5"
parking_lot = "0.5"
rand = "0.4"
ring = "0.12"
rlp = { path = "../util/rlp" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slab = "0.3"
smallvec = "0.4"
tiny-keccak = "1.3"

jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.11" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.11" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.11" }
