[package]
description = "Parity Ethereum Whisper Protocol Implementation"
name = "parity-whisper"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
bitflags = "0.9"
byteorder = "1.0.0"
ethereum-types = "0.4"
ethcore-network = { path = "../util/network" }
parity-crypto = "0.3.0"
ethkey = { path = "../accounts/ethkey" }
hex = "0.2"
log = "0.4"
memzero = { path = "../util/memzero" }
ordered-float = "0.5"
parking_lot = "0.7"
rand = "0.4"
rlp = { version = "0.3.0", features = ["ethereum"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
slab = "0.3"
smallvec = "0.6"
tiny-keccak = "1.4"
time-utils = { path = "../util/time-utils" }

jsonrpc-core = "14.0.3"
jsonrpc-derive = "14.0.3"
jsonrpc-pubsub = "14.0.3"
