[package]
description = "Non-instant BFT proof-of-authority blockchain engine"
name = "authority-round"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
block-gas-limit = { path = "../../block-gas-limit" }
block-reward = { path = "../../block-reward" }
client-traits = { path = "../../client-traits" }
common-types = { path = "../../types" }
derive_more = "0.99"
ethabi = "12.0"
ethabi-contract = "11.0"
ethabi-derive = "12.0"
ethereum-types = "0.9.2"
ethjson = { path = "../../../json" }
parity-crypto = { version = "0.6.2", features = ["publickey"] }
engine = { path = "../../engine" }
io = { package = "ethcore-io", path = "../../../util/io" }
itertools = "0.8.2"
keccak-hash = "0.5.0"
lazy_static = "1.3.0"
log = "0.4"
lru-cache = "0.1"
machine = { path = "../../machine" }
parity-bytes = "0.1"
parking_lot = "0.10.0"
rand = "0.7.3"
rlp = "0.4.5"
time-utils = { path = "../../../util/time-utils" }
unexpected = { path = "../../../util/unexpected" }
validator-set = { path = "../validator-set" }

[dev-dependencies]
accounts = { package = "ethcore-accounts", path = "../../../accounts" }
engine = { path = "../../engine", features = ["test-helpers"] }
env_logger = "0.6.2"
ethcore = { path = "../..", features = ["test-helpers"] }
spec = { path = "../../spec" }
state-db = { path = "../../state-db" }
validator-set = { path = "../validator-set", features = ["test-helpers"] }
serde_json = "1"
