[package]
description = "Parity Smart Contract based Node Filter, Manage Permissions of Network Connections"
repository = "https://github.com/openethereum/openethereum"
license = "GPL-3.0"
name = "node-filter"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
client-traits = { path = "../client-traits" }
common-types = { path = "../types" }
ethcore = { path = ".."}
ethcore-network = { path = "../../util/network" }
ethcore-network-devp2p = { path = "../../util/network-devp2p" }
ethereum-types = "0.9.0"
log = "0.4"
parking_lot = "0.10.0"
ethabi = "12.0"
ethabi-derive = "12.0"
ethabi-contract = "9.0.0"
lru-cache = "0.1"

[dev-dependencies]
ethcore = { path = "..", features = ["test-helpers"] }
kvdb-memorydb = "0.5.0"
ethcore-io = { path = "../../util/io" }
spec = { path = "../spec" }
tempfile = "3.1"
