# NOTE This file is used by the auto-updater service.
# Make sure to update the service if it's moved or the structure is changed.
[package]
name = "parity-version"
# NOTE: this value is used for Parity Ethereum version string (via env CARGO_PKG_VERSION)
version = "2.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[package.metadata]
# This versions track. Should be changed to `stable` or `beta` when on respective branches.
# Used by auto-updater and for Parity version string.
track = "nightly"

# Network specific settings, used ONLY by auto-updater.
# Latest supported fork blocks.
# Indicates a critical release in this track (i.e. consensus issue).
[package.metadata.networks]
foundation = { forkBlock = 4370000, critical = false }
ropsten = { forkBlock = 10, critical = false }
kovan = { forkBlock = 6600000, critical = false }

[dependencies]
parity-bytes = "0.1"
rlp = { version = "0.2.4", features = ["ethereum"] }
target_info = "0.1"

[build-dependencies]
vergen = "0.1"
rustc_version = "0.2"
toml = "0.4"

[features]
final = []
