[package]
name = "parity-version"
# NOTE: this value is used for Parity Ethereum version string (via env CARGO_PKG_VERSION)
version = "2.5.13"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[package.metadata]

[dependencies]
parity-bytes = "0.1"
rlp = { version = "0.3.0", features = ["ethereum"] }
target_info = "0.1"

[build-dependencies]
vergen = "0.1"
rustc_version = "0.2"
toml = "0.4"

[features]
final = []
