[package]
name = "rlp_derive"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[lib]
name = "rlp_derive"
proc-macro = true

[dependencies]
syn = "0.13"
quote = "0.5"

[dev-dependencies]
rlp = "0.2.4"
