[package]
name = "ethcore-ipc-nano"
version = "1.1.0"
authors = ["Nikolay Volf <nikolay@ethcore.io>"]
license = "GPL-3.0"

[features]

[dependencies]
jsonrpc-core = "2.0"
"ethcore-ipc" = { path = "../rpc" }
nanomsg = { git = "https://github.com/ethcore/nanomsg.rs.git" }
log = "0.3"

