[package]
name = "ethcore-ipc-nano"
version = "1.7.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"

[features]

[dependencies]
ethcore-ipc = { path = "../rpc" }
nanomsg = { git = "https://github.com/ethcore/nanomsg.rs.git" }
log = "0.3"
lazy_static = "0.2"
