[package]
name = "ethcore-ipc-nano"
version = "1.4.0"
authors = ["Nikolay Volf <nikolay@ethcore.io>"]
license = "GPL-3.0"

[features]

[dependencies]
ethcore-ipc = { path = "../rpc" }
nanomsg = { git = "https://github.com/thehydroimpulse/nanomsg.rs.git", features = ["bundled"] }
log = "0.3"

