[package]
description = "Virtual Machines (VM) Support Library"
name = "vm"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
parity-bytes = "0.1"
ethereum-types = "0.6.0"
patricia-trie-ethereum = { path = "../../util/patricia-trie-ethereum" }
ethjson = { path = "../../json" }
rlp = "0.4.0"
keccak-hash = "0.2.0"
