[package]
description = "Ethcore stratum lib"
name = "ethcore-stratum"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethereum-types = "0.9.0"
keccak-hash = "0.5.0"
jsonrpc-core = { git = "https://github.com/adria0/jsonrpc", branch="adria0/rawapi"} 
jsonrpc-tcp-server = { git = "https://github.com/adria0/jsonrpc", branch="adria0/rawapi"}
log = "0.4"
parking_lot = "0.10.0"

[dev-dependencies]
env_logger = "0.5"
tokio = "0.1"
tokio-io = "0.1"
