[package]
description = "Ethcore stratum lib"
name = "ethcore-stratum"
version = "1.12.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethereum-types = "0.6.0"
keccak-hash = "0.2.0"
jsonrpc-core = "12.0.0"
jsonrpc-tcp-server = "12.0.0"
log = "0.4"
parking_lot = "0.7"

[dev-dependencies]
env_logger = "0.5"
tokio = "0.1"
tokio-io = "0.1"
