[package]
description = "Ethcore blockchain sync"
name = "ethsync"
version = "1.11.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[lib]

[dependencies]
ethcore-bytes = { path = "../util/bytes" }
ethcore-network = { path = "../util/network" }
ethcore-io = { path = "../util/io" }
ethcore-light = { path = "../ethcore/light" }
ethcore-transaction = { path = "../ethcore/transaction" }
ethcore = { path = "../ethcore" }
ethereum-types = "0.2"
plain_hasher = { path = "../util/plain_hasher" }
rlp = { path = "../util/rlp" }
keccak-hash = { path = "../util/hash" }
triehash = { path = "../util/triehash" }
kvdb = { path = "../util/kvdb" }
macros = { path = "../util/macros" }
log = "0.3"
env_logger = "0.4"
time = "0.1.34"
rand = "0.4"
heapsize = "0.4"
semver = "0.6"
smallvec = { version = "0.4", features = ["heapsizeof"] }
parking_lot = "0.5"
ipnetwork = "0.12.6"

[dev-dependencies]
ethkey = { path = "../ethkey" }
kvdb-memorydb = { path = "../util/kvdb-memorydb" }
