[package]
description = "A crate to interact with the block rewards contract."
name = "block-reward"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
common-types = { path = "../types" }
engine = { path = "../engine" }
ethabi = "12.0"
ethabi-derive = "12.0"
ethabi-contract = "11.0"
ethereum-types = "0.9.2"
keccak-hash = "0.5.0"
machine = { path = "../machine" }
trace = { path = "../trace" }

[dev-dependencies]
ethcore = { path = "..", features = ["test-helpers"] }
spec = { path = "../spec" }
