[package]
description = "Manage validators and sets of validators: creation, calling and validation of contracts, epoch management, proofs and proving"
name = "validator-set"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { path = "../../client-traits" }
common-types = { path = "../../types" }
engine = { path = "../../engine" }
ethabi = "8.0.1"
ethabi-contract = "8.0.1"
ethabi-derive = "8.0.0"
ethereum-types = "0.6.0"
ethjson = { path = "../../../json" }
executive-state = { path = "../../executive-state" }
keccak-hash = "0.2.0"
kvdb = "0.1.0"
lazy_static = "1.3.0"
log = "0.4.8"
machine = { path = "../../machine" }
memory-cache = { path = "../../../util/memory-cache" }
parity-bytes = "0.1.0"
parity-util-mem = "0.2.0"
parking_lot = "0.8"
rlp = "0.4.2"
triehash = { package = "triehash-ethereum", version = "0.2",  path = "../../../util/triehash-ethereum" }
unexpected = { path = "../../../util/unexpected" }
vm = { path = "../../vm" }

[dev-dependencies]
accounts = { package = "ethcore-accounts", path = "../../../accounts" }
call-contract = { package = "ethcore-call-contract", path = "../../call-contract" }
engine = { path = "../../engine", features = ["test-helpers"] }
env_logger = "0.6.2"
ethcore = { path = "../..", features = ["test-helpers"] }
ethkey = { path = "../../../accounts/ethkey" }
keccak-hash = "0.2.0"
rustc-hex = "1.0"
spec = { path = "../../spec" }

[features]
test-helpers = []
