[package]
name = "journaldb"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "A `HashDB` which can manage a short-term journal potentially containing many forks of mutually exclusive actions"
license = "GPL3"

[dependencies]
parity-bytes = "0.1"
ethereum-types = "0.6.0"
hash-db = "0.12.4"
parity-util-mem = "0.1"
keccak-hasher = { path = "../keccak-hasher" }
kvdb = "0.1"
log = "0.4"
memory-db = "0.12.4"
parking_lot = "0.7"
fastmap = { path = "../../util/fastmap" }
rlp = "0.4.0"

[dev-dependencies]
env_logger = "0.5"
keccak-hash = "0.2.0"
kvdb-memorydb = "0.1"
