[package]
name = "journaldb"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "A `HashDB` which can manage a short-term journal potentially containing many forks of mutually exclusive actions"
license = "GPL3"

[dependencies]
parity-bytes = { git = "https://github.com/paritytech/parity-common" }
ethereum-types = "0.3"
hashdb = { git = "https://github.com/paritytech/parity-common" }
heapsize = "0.4"
keccak-hasher = { path = "../keccak-hasher" }
kvdb = { git = "https://github.com/paritytech/parity-common" }
log = "0.3"
memorydb = { git = "https://github.com/paritytech/parity-common" }
parking_lot = "0.6"
fastmap = { path = "../../util/fastmap" }
rlp = { git = "https://github.com/paritytech/parity-common" }

[dev-dependencies]
ethcore-logger = { path = "../../logger" }
keccak-hash = { git = "https://github.com/paritytech/parity-common" }
kvdb-memorydb = { git = "https://github.com/paritytech/parity-common" }
