[package]
name = "migration-rocksdb"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.4"
macros = { path = "../macros" }
kvdb = "0.1.0"
kvdb-rocksdb = "0.1.3"

[dev-dependencies]
tempdir = "0.3"
