[package]
description = "Ethcore Trusted Signer"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-signer"
version = "1.7.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.1"

[dependencies]
rand = "0.3.14"
jsonrpc-core = { git = "https://github.com/ethcore/jsonrpc.git" }
log = "0.3"
env_logger = "0.3"
parity-dapps-glue = { version = "1.4", optional = true }
ws = { git = "https://github.com/ethcore/ws-rs.git", branch = "mio-upstream-stable" }
ethcore-util = { path = "../util" }
ethcore-io = { path = "../util/io" }
ethcore-rpc = { path = "../rpc" }
ethcore-devtools = { path = "../devtools" }
parity-ui = { path = "../dapps/ui", version = "1.4", optional = true }

clippy = { version = "0.0.103", optional = true}

[features]
dev = ["clippy"]
ui = ["parity-dapps-glue", "parity-ui", "parity-ui/no-precompiled-js"]
ui-precompiled = ["parity-dapps-glue", "parity-ui", "parity-ui/use-precompiled-js"]
