[package]
description = "Ethcore Trusted Signer"
homepage = "http://ethcore.io"
license = "GPL-3.0"
name = "ethcore-signer"
version = "1.4.0"
authors = ["Ethcore <admin@ethcore.io>"]
build = "build.rs"

[build-dependencies]
rustc_version = "0.1"

[dependencies]
rand = "0.3.14"
jsonrpc-core = "3.0"
log = "0.3"
env_logger = "0.3"
ws = { git = "https://github.com/ethcore/ws-rs.git", branch = "mio-upstream-stable" }
ethcore-util = { path = "../util" }
ethcore-io = { path = "../util/io" }
ethcore-rpc = { path = "../rpc" }
ethcore-devtools = { path = "../devtools" }
parity-dapps-glue = { path = "../dapps/js-glue", version = "1.4", optional = true}
parity-ui = { path = "../dapps/ui", version = "1.4", optional = true}

clippy = { version = "0.0.90", optional = true}

[features]
dev = ["clippy"]
ui = ["parity-dapps-glue", "parity-ui"]
use-precompiled-js = ["parity-ui/use-precompiled-js"]

