[package]
description = "Clique consensus engine"
name = "clique"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
client-traits = { path = "../../client-traits" }
common-types = { path = "../../types" }
ethereum-types = "0.9.0"
ethjson = { path = "../../../json" }
parity-crypto = { version = "0.6.0", features = ["publickey"] }
engine = { path = "../../engine" }
keccak-hash = "0.5.0"
lazy_static = "1.3.0"
log = "0.4"
lru-cache = "0.1"
machine = { path = "../../machine" }
rand = "0.7.3"
parking_lot = "0.10.0"
rlp = "0.4.5"
time-utils = { path = "../../../util/time-utils" }
unexpected = { path = "../../../util/unexpected" }

[dev-dependencies]
ethcore = { path = "../..", features = ["test-helpers"] }
spec = { path = "../../spec" }
state-db = { path = "../../state-db" }
