[package]
name = "snapshot-tests"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
accounts = { package = "ethcore-accounts", path = "../../../accounts" }
account-db = { path = "../../account-db" }
account-state = { path = "../../account-state" }
blockchain = { package = "ethcore-blockchain", path = "../../blockchain" }
bytes = { package = "parity-bytes", version = "0.1.0" }
client-traits = { path = "../../client-traits" }
common-types = { path = "../../types" }
engine = { path = "../../engine", features = ["test-helpers"] }
env_logger = "0.5"
ethcore = { path = "../..", features = ["test-helpers"] }
ethcore-db = { path = "../../db" }
ethcore-io = { path = "../../../util/io" }
ethereum-types = "0.9.1"
ethtrie  = { package = "patricia-trie-ethereum", path = "../../../util/patricia-trie-ethereum" }
hash-db = "0.15.0"
journaldb = { path = "../../../util/journaldb" }
keccak-hash = "0.5.0"
keccak-hasher = { path = "../../../util/keccak-hasher" }
kvdb = "0.6"
kvdb-rocksdb = "0.8"
log = "0.4.8"
parking_lot = "0.10.0"
parity-crypto = { version = "0.6.1", features = ["publickey"] }
rand = "0.7.3"
rand_xorshift = "0.2.0"
rlp = "0.4.5"
snappy = { package = "parity-snappy", version ="0.1.0" }
snapshot = { path = "../../snapshot", features = ["test-helpers"] }
spec = { path = "../../spec" }
tempfile = "3.1"
trie-db = "0.20.0"
trie-standardmap = "0.15.0"
ethabi = "12.0"
ethabi-contract = "11.0"
ethabi-derive = "12.0"
lazy_static = { version = "1.3" }
triehash = { package = "triehash-ethereum", version = "0.2",  path = "../../../util/triehash-ethereum" }
