[package]
description = "Large fixed-size integers and hash function outputs"
homepage = "http://parity.io"
repository = "https://github.com/paritytech/parity"
license = "MIT/Apache-2.0"
name = "ethcore-bigint"
version = "0.1.3"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
bigint = "4.0"
rustc-hex = "1.0"
rand = "0.3.12"
libc = "0.2"
heapsize = { version = "0.4", optional = true }

[features]
x64asm_arithmetic=[]
rust_arithmetic=[]
heapsizeof = ["heapsize", "bigint/heapsizeof"]
