[package]
name = "eip-2124"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
repository = "https://github.com/paritytech/parity-ethereum"
documentation = "https://docs.rs/eip-2124"
readme = "README.md"
description = "EIP-2124 Fork ID implementation"
keywords = ["eip-2124", "eip"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
crc = "1"
ethereum-types = "0.8.0"
maplit = "1"
rlp = "0.4"

[dev-dependencies]
hex-literal = "0.2"
