[package]
name = "ethstore-cli"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rustc-hex = "1.0"
docopt = "0.7"
ethstore = { path = "../" }

[[bin]]
name = "ethstore"
path = "src/main.rs"
doc = false
