[package]
description = "Parity IPFS-compatible API"
name = "parity-ipfs-api"
version = "1.8.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethcore = { path = "../ethcore" }
ethcore-util = { path = "../util" }
ethcore-bigint = { path = "../util/bigint" }
ethcore-bytes = { path = "../util/bytes" }
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.7" }
rlp = { path = "../util/rlp" }
mime = "0.2"
cid = "0.2"
multihash = "0.6"
