[package]
name = "memzero"
version = "0.1.0"
description = "A wrapper for zero-ing out memory when dropped"
license = "GPL-3.0"
homepage = "https://parity.io"
repository = "https://github.com/paritytech/parity-ethereum"
docs = "https://docs.rs/crate/memzero"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
