[package]
description = "Parity WebApplications crate"
name = "ethcore-webapp"
version = "1.1.0"
license = "GPL-3.0"
authors = ["Ethcore <admin@ethcore.io"]

[lib]

[dependencies]
log = "0.3"
jsonrpc-core = { git = "https://github.com/tomusdrw/jsonrpc-core.git" }
jsonrpc-http-server = { git = "https://github.com/tomusdrw/jsonrpc-http-server.git", version = "5.1.0" }
hyper = { default-features = false, git = "https://github.com/hyperium/hyper", branch = "mio" }
url = "1.0"
ethcore-rpc = { path = "../rpc" }
ethcore-util = { path = "../util" }
parity-webapp = { git = "https://github.com/tomusdrw/parity-webapp.git" }
# List of apps
parity-status = { git = "https://github.com/tomusdrw/parity-status.git", version = "0.3.6" }
parity-wallet = { git = "https://github.com/tomusdrw/parity-wallet.git", optional = true }
clippy = { version = "0.0.64", optional = true}

[features]
default = []
dev = ["clippy", "ethcore-rpc/dev", "ethcore-util/dev"]
