[package]
description = "Parity Light Client Implementation"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-light"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.3"
ethcore = { path = ".."}
parity-bytes = { git = "https://github.com/paritytech/parity-common", rev = "1803c0f" }
ethcore-transaction = { path = "../transaction" }
ethereum-types = "0.3"
memorydb = { git = "https://github.com/paritytech/parity-common", rev = "1803c0f" }
patricia-trie = { git = "https://github.com/paritytech/parity-common", rev = "1803c0f" }
patricia-trie-ethereum = { path = "../../util/patricia-trie-ethereum" }
ethcore-network = { path = "../../util/network" }
ethcore-io = { path = "../../util/io" }
hashdb = { git = "https://github.com/paritytech/parity-common", rev = "1803c0f" }
heapsize = "0.4"
vm = { path = "../vm" }
plain_hasher = { git = "https://github.com/paritytech/parity-common", rev = "1803c0f" }
rlp = { git = "https://github.com/paritytech/parity-common", rev = "1803c0f" }
rlp_derive = { path = "../../util/rlp_derive" }
smallvec = "0.4"
futures = "0.1"
rand = "0.4"
itertools = "0.5"
bincode = "0.8.0"
serde = "1.0"
serde_derive = "1.0"
parking_lot = "0.6"
stats = { path = "../../util/stats" }
keccak-hash = { git = "https://github.com/paritytech/parity-common", rev = "1803c0f" }
keccak-hasher = { path = "../../util/keccak-hasher" }
triehash-ethereum = { version = "0.2",  path = "../../util/triehash-ethereum" }
kvdb = { git = "https://github.com/paritytech/parity-common", rev = "1803c0f" }
memory-cache = { path = "../../util/memory_cache" }
error-chain = { version = "0.12", default-features = false }

[dev-dependencies]
ethcore = { path = "..", features = ["test-helpers"] }
kvdb-memorydb = { path = "../../util/kvdb-memorydb" }
tempdir = "0.3"

[features]
default = []
