[package]
name = "trace"
description = "Transaction tracing"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
ethcore-blockchain = { path = "../blockchain" }
ethcore-db = { path = "../db" }
ethereum-types = "0.9.2"
evm = { path = "../evm" }
kvdb = "0.7"
log = "0.4"
parity-bytes = "0.1.0"
parity-util-mem = "0.7"
parking_lot = "0.10.0"
rlp = "0.4.5"
rlp-derive = "0.1"
vm = { path = "../vm" }

[dev-dependencies]
# Used for test helpers
ethcore = { path = "..", features = ["test-helpers"] }
