[package]
name = "trace"
description = "Transaction tracing"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "GPL-3.0"
edition = "2018"

[dependencies]
ethcore-blockchain = { path = "../blockchain" }
ethcore-db = { path = "../db" }
ethereum-types = "0.6"
evm = { path = "../evm" }
kvdb = "0.1"
log = "0.4"
parity-bytes = "0.1.0"
parity-util-mem = "0.2.0"
parking_lot = "0.9"
rlp = "0.4.0"
rlp_derive = { path = "../../util/rlp-derive" }
vm = { path = "../vm" }

[dev-dependencies]
# Used for test helpers
ethcore = { path = "..", features = ["test-helpers"] }
