[package]
name = "common-types"
description = "Common types used throughout the codebase"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
rlp = { version = "0.3.0", features = ["ethereum"] }
rlp_derive = { path = "../../util/rlp-derive" }
parity-bytes = "0.1"
ethereum-types = "0.4"
ethjson = { path = "../../json" }
keccak-hash = "0.1"
heapsize = "0.4"

[dev-dependencies]
rustc-hex= "1.0"
