[package]
description = "OpenEthereum Common Types"
name = "common-types"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
bytes = { package = "parity-bytes", version = "0.1" }
derive_more = "0.99"
ethbloom = "0.9.0"
ethcore-io = { path = "../../util/io" }
ethereum-types = "0.9.0"
ethjson = { path = "../../json" }
hash = { package = "keccak-hash", version = "0.5" }
parity-crypto = { version = "0.6.1", features = ["publickey"] }
parity-util-mem = "0.6.0"
ethtrie = { package = "patricia-trie-ethereum", path = "../../util/patricia-trie-ethereum" }
rlp = "0.4.5"
rlp-derive = "0.1"
snap = "1"
unexpected = { path = "../../util/unexpected" }
vm = { path = "../vm"}

[dev-dependencies]
rustc-hex = "2.1.0"

[features]
test-helpers = []
